"""Fix _forward_via_nm: wait for first chunk before sending head."""
PATH = "D:/proxy-bridge/local_proxy.py"

with open(PATH, "rb") as f:
    data = f.read()

fn_start = data.index(b"def _forward_via_nm(")
fn_end = data.index(b"\r\ndef _forward_via_urllib(", fn_start) + 2

new_fn = (
    b'def _forward_via_nm(sock, method, url, headers, body):\r\n'
    b'    """Forward request through Chrome Native Messaging and stream response back."""\r\n'
    b'    clean_headers = {}\r\n'
    b'    drop_request = {"connection", "proxy-connection", "keep-alive", "host"}\r\n'
    b'    for k, v in headers.items():\r\n'
    b'        kl = k.lower()\r\n'
    b'        if kl not in drop_request:\r\n'
    b'            clean_headers[k] = v\r\n'
    b'\r\n'
    b'    if body and len(body) >= 2 and body[:2] == b\'\\x1f\\x8b\':\r\n'
    b'        ce_key = None\r\n'
    b'        for k in headers:\r\n'
    b'            if k.lower() == \'content-encoding\':\r\n'
    b'                ce_key = k\r\n'
    b'                break\r\n'
    b'        if ce_key is None:\r\n'
    b'            clean_headers[\'Content-Encoding\'] = \'gzip\'\r\n'
    b'            logger.debug("NM_GZIP_AUTO: added Content-Encoding: gzip for %d-byte body", len(body))\r\n'
    b'\r\n'
    b'    with utils.nm_lock:\r\n'
    b'        req_id = utils.nm_request_id_counter\r\n'
    b'        utils.nm_request_id_counter += 1\r\n'
    b'\r\n'
    b'    resp_event = threading.Event()\r\n'
    b'    end_event = threading.Event()\r\n'
    b'    resp_data = {"status": 502, "statusText": "Bad Gateway", "headers": {}, "chunks": [], "error": None}\r\n'
    b'\r\n'
    b'    def handler(msg):\r\n'
    b'        mtype = msg.get("type", "")\r\n'
    b'        mid = msg.get("id")\r\n'
    b'        if mid != req_id:\r\n'
    b'            return\r\n'
    b'        if mtype == "response":\r\n'
    b'            resp_data["status"] = msg.get("status", 200)\r\n'
    b'            resp_data["statusText"] = msg.get("statusText", "OK")\r\n'
    b'            resp_data["headers"] = msg.get("headers", {})\r\n'
    b'            resp_event.set()\r\n'
    b'        elif mtype == "chunk":\r\n'
    b'            b64 = msg.get("data", "")\r\n'
    b'            if b64:\r\n'
    b'                resp_data["chunks"].append(base64.b64decode(b64))\r\n'
    b'        elif mtype == "end":\r\n'
    b'            end_event.set()\r\n'
    b'        elif mtype == "error":\r\n'
    b'            resp_data["error"] = msg.get("error", "Unknown error")\r\n'
    b'            resp_event.set()\r\n'
    b'            end_event.set()\r\n'
    b'\r\n'
    b'    utils.nm_pending_requests[req_id] = handler\r\n'
    b'\r\n'
    b'    try:\r\n'
    b'        utils.nm_send_msg({"type": "request_start", "id": req_id, "method": method, "url": url, "headers": clean_headers})\r\n'
    b'        if body:\r\n'
    b'            chunk_max = 512 * 1024\r\n'
    b'            for offset in range(0, len(body), chunk_max):\r\n'
    b'                chunk = body[offset:offset + chunk_max]\r\n'
    b'                utils.nm_send_msg({"type": "request_chunk", "id": req_id, "data": base64.b64encode(chunk).decode("ascii")})\r\n'
    b'        utils.nm_send_msg({"type": "request_end", "id": req_id})\r\n'
    b'\r\n'
    b'        if not resp_event.wait(timeout=120):\r\n'
    b'            raise Exception("NM response timeout (120s)")\r\n'
    b'        if resp_data["error"]:\r\n'
    b'            raise Exception(f"NM error: {resp_data[\'error\']}")\r\n'
    b'\r\n'
    b'        # Wait for at least one chunk before sending head\r\n'
    b'        # Prevents client timeout while NM waits for upstream response\r\n'
    b'        while len(resp_data["chunks"]) == 0 and not end_event.is_set():\r\n'
    b'            end_event.wait(0.1)\r\n'
    b'\r\n'
    b'        upstream_cl = _hdr(resp_data["headers"], "Content-Length") or ""\r\n'
    b'        resp_headers = resp_data["headers"]\r\n'
    b'        drop_resp = {"connection", "proxy-connection", "keep-alive", "transfer-encoding", "content-encoding"}\r\n'
    b'        head = f"HTTP/1.1 {resp_data[\'status\']} {resp_data[\'statusText\']}\\r\\n"\r\n'
    b'        for k, v in resp_headers.items():\r\n'
    b'            kl = k.lower()\r\n'
    b'            if kl == "set-cookie" and isinstance(v, list):\r\n'
    b'                for cv in v:\r\n'
    b'                    head += f"Set-Cookie: {cv}\\r\\n"\r\n'
    b'            elif kl not in drop_resp:\r\n'
    b'                head += f"{k}: {v}\\r\\n"\r\n'
    b'        if upstream_cl:\r\n'
    b'            head += f"Content-Length: {upstream_cl}\\r\\n"\r\n'
    b'        head += "Connection: close\\r\\n\\r\\n"\r\n'
    b'        sock.sendall(head.encode("utf-8"))\r\n'
    b'\r\n'
    b'        # Stream body: send chunks as they arrive, no further buffering\r\n'
    b'        idx = 0\r\n'
    b'        deadline = time.time() + 600\r\n'
    b'        while True:\r\n'
    b'            while idx < len(resp_data["chunks"]):\r\n'
    b'                try:\r\n'
    b'                    sock.sendall(resp_data["chunks"][idx])\r\n'
    b'                except Exception:\r\n'
    b'                    end_event.set()\r\n'
    b'                    break\r\n'
    b'                idx += 1\r\n'
    b'            if end_event.is_set() and idx >= len(resp_data["chunks"]):\r\n'
    b'                break\r\n'
    b'            end_event.wait(0.1)\r\n'
    b'            if time.time() > deadline:\r\n'
    b'                logger.debug("NM_STREAM_TIMEOUT")\r\n'
    b'                break\r\n'
    b'        logger.debug("NM_STREAMED: sent=%d chunks", idx)\r\n'
    b'\r\n'
    b'    except Exception as e:\r\n'
    b'        logger.debug("_forward_via_nm error: %s", e)\r\n'
    b'        try:\r\n'
    b'            sock.sendall(b"HTTP/1.1 502 Bad Gateway\\r\\nContent-Length: 0\\r\\nConnection: close\\r\\n\\r\\n")\r\n'
    b'        except Exception:\r\n'
    b'            pass\r\n'
    b'    finally:\r\n'
    b'        utils.nm_pending_requests.pop(req_id, None)\r\n'
)

data = data[:fn_start] + new_fn + data[fn_end:]
with open(PATH, "wb") as f:
    f.write(data)

import py_compile
py_compile.compile(PATH, doraise=True)
print("SUCCESS")
